'use client'
import { useEffect, useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import { useApp } from '@/lib/context'
import Icon from '@/components/ui/Icon'
type ProfileData = { user:{name:string;sap_id:string;shift_number?:number;total_score:number}; rank:number|null;shift_rank:number|null;total_drivers:number;shift_drivers:number;quiz_attempts:Array<{id:string;score:number;completed_at:string;quiz?:{title:string;active_date:string}}> ;game_attempts:Array<{id:string;score:number;played_at:string;game?:{title:string;template:string}}> }
type Activity = { id:string; type:'quiz'|'game'; title:string; date:string; score:number }
export default function ProfilePage(){
 const{user,ready,logout}=useApp();const router=useRouter();const[data,setData]=useState<ProfileData|null>(null)
 useEffect(()=>{if(!ready)return;if(!user){router.push('/login');return}fetch(`/api/profile?user_id=${user.id}`).then(r=>r.json()).then(result=>setData(result.data??null))},[ready,user,router])
 const activity=useMemo<Activity[]>(()=>data?[...data.quiz_attempts.map(item=>({id:item.id,type:'quiz' as const,title:item.quiz?.title||'Өдрийн асуумж',date:item.completed_at,score:item.score})),...data.game_attempts.map(item=>({id:item.id,type:'game' as const,title:item.game?.title||'Мэдлэг сэргээх тоглоом',date:item.played_at,score:item.score}))].sort((a,b)=>b.date.localeCompare(a.date)):[],[data])
 if(!user)return null
 if(!data)return <div className="empty-state"><span className="spinner"/>Профайл ачааллаж байна...</div>
 return <div className="app-container page-enter"><section className="profile-hero card"><div className="profile-avatar">{data.user.name[0]}</div><div><span className="eyebrow">ЖОЛООЧИЙН ПРОФАЙЛ</span><h1>{data.user.name}</h1><p>SAP {data.user.sap_id} · {data.user.shift_number?`${data.user.shift_number}-р ээлж`:'Ээлж тохируулаагүй'}</p></div></section><div className="profile-ranks"><div><Icon name="trophy"/><span>Нийт rank</span><strong>{data.rank?`#${data.rank}`:'—'}</strong><small>{data.total_drivers} жолоочоос</small></div><div><Icon name="users"/><span>Ээлжийн rank</span><strong>{data.shift_rank?`#${data.shift_rank}`:'—'}</strong><small>{data.shift_drivers} жолоочоос</small></div><div><Icon name="check"/><span>Нийт оноо</span><strong>{data.user.total_score.toLocaleString()}</strong><small>{activity.length} оролдлого</small></div></div><section className="card activity-card"><div className="section-heading"><div><span className="eyebrow">ТҮҮХ</span><h2>Сүүлийн үйл ажиллагаа</h2></div></div>{activity.length===0?<div className="empty-mini">Асуумж, тоглоомын түүх хараахан байхгүй.</div>:activity.map(item=><div className="activity-row" key={`${item.type}-${item.id}`}><div className={`activity-icon ${item.type}`}><Icon name={item.type==='quiz'?'clipboard':'game'} size={19}/></div><div><strong>{item.title}</strong><small>{new Intl.DateTimeFormat('mn-MN',{year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(item.date))}</small></div><b>+{item.score}</b></div>)}</section><button className="btn-quiet logout-wide" onClick={()=>{logout();router.push('/login')}}><Icon name="logout" size={18}/>Системээс гарах</button></div>
}
